CREATE TABLE FRIENDS_P2(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FRIEND_ONE VARCHAR(25) NOT NULL,
    FRIEND_TWO VARCHAR(25) NOT NULL,
    STATUS INT NOT NULL,
    TIME_STAMP VARCHAR(50) NOT NULL
);