CREATE TABLE POSTCARDS_P2(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AUTHOR VARCHAR(25) NOT NULL,
	RECIP VARCHAR(25) NOT NULL,
	IMAGE_NAME VARCHAR(50) NOT NULL,
	FILTER VARCHAR(50) NOT NULL,
	IMAGE_TEXT VARCHAR(140) NOT NULL,
	IMAGE_TITLE VARCHAR(50) NOT NULL,
	TIME_STAMP VARCHAR(50) NOT NULL
);