CREATE TABLE USERS_P2(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    PROFILE_IMG VARCHAR(50),
    TIME_STAMP VARCHAR(50) NOT NULL
);
